\documentclass[article]{jss}

%%%
%%% TITLE:       fitdistrplus: an R Package for Distribution Fitting Methods
%%% AUTHORS:     Marie Laure Delignette Muller*, Christophe Dutang
%%%              * Corresponding author
%%% AFFILIATION: LBBE, Université Claude Bernard Lyon 1, Lyon, France
%%% ADDRESS:     VetAgro Sup Campus Vétérinaire de Lyon
%%%              1, avenue Bourgelat
%%%              69820 MARCY L'ETOILE, France
%%% PHONE:       +33 4 78 87 27 40
%%% FAX:         +33 4 78 87 27 12
%%% EMAIL:       marielaure.delignettemuller@vetagro-sup.fr
%%%



\usepackage{amsmath,amsthm}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
%% need no \usepackage{Sweave.sty}

\usepackage{wrapfig, subfig}
%\usepackage[a4paper, textwidth=18cm, textheight=27cm]{geometry}



  
\author{ Marie Laure Delignette-Muller \\ Université Claude Bernard Lyon 1 \And
    Christophe Dutang \\ Université de Strasbourg}
\Plainauthor{Marie Laure Delignette-Muller}

\title{\pkg{fitdistrplus}: An \proglang{R} Package for Distribution Fitting Methods}
\Plaintitle{fitdistrplus: an R Package for Distribution Fitting Methods}

\Abstract{%
    blabla.}

\Keywords{distributions, censored data, \proglang{R}}
\Plainkeywords{distributions, censored data, R}

%% publication information
%% NOTE: Typically, this can be left commented and will be filled out by the technical editor
%% \Volume{50}
%% \Issue{9}
%% \Month{June}
%% \Year{2012}
%% \Submitdate{2012-09-04}
%% \Acceptdate{2012-09-04}

\Address{
    Marie Laure Delignette-Muller \\
    VetAgro Sup Campus Vétérinaire de Lyon \\
    1, avenue Bourgelat \\
    69820 MARCY L'ETOILE\\
    France \\
    E-mail: \email{marielaure.delignettemuller@vetagro-sup.fr} \\
    URL: \url{http://lbbe.univ-lyon1.fr/-Delignette-Muller-Marie-Laure-.html}
}


\newcommand{\Sconcordance}[1]{%
  \ifx\pdfoutput\undefined%
  \csname newcount\endcsname\pdfoutput\fi%
  \ifcase\pdfoutput\special{#1}%
  \else%
   \begingroup%
     \pdfcompresslevel=0%
     \immediate\pdfobj stream{#1}%
     \pdfcatalog{/SweaveConcordance \the\pdflastobj\space 0 R}%
   \endgroup%
  \fi}


\begin{document}
\SweaveOpts{concordance=TRUE, prefix.string=figs/jss}



%% include your article here, just as usual
%% Note that you should use the \pkg{}, \proglang{} and \code{} commands.



This manuscript reviews the various features of version 1.0-0 of \pkg{fitdistrplus}. The package
is available from the Comprehensive \proglang{R} Archive Network at \url{http://cran.r-project.org/package=fitdistrplus}.
The development version of the package is located at \proglang{R}-forge as one the packages of the 
project ``Risk Assessment with R''
(\url{http://r-forge.r-project.org/projects/riskassessment/})
The following command will load the package.
%%% R code set default options for all R schunks
<<par4vignette, echo=FALSE, results=hide>>=
options(digits=4, SweaveHooks=list(fig=function() par(mar=c(5.1, 4.1, 1.1, 2.1))) )
@
%%% R code
<<pkgload1, results=hide>>=
library(fitdistrplus)
@


%\section*{Acknowledgments}

%\bibliography{fitdistrplus}


 
\end{document}
